#pragma once

#define PLAYTT_FIRMWARE_VERSION "esp32s3-v1.0.0"
#define PLAYTT_DEFAULT_BASE_URL "https://www.theplaytt.com"
#define PLAYTT_HEARTBEAT_MS 15000
#define PLAYTT_DEBOUNCE_MS 80
#define PLAYTT_HTTP_TIMEOUT_MS 15000
#define PLAYTT_MAX_EVENT_QUEUE 32
#define PLAYTT_HTTP_BODY_MAX 4096

#define PLAYTT_GPIO_SIDE_A 4
#define PLAYTT_GPIO_SIDE_B 5
#define PLAYTT_GPIO_LED 2
#define PLAYTT_GPIO_BOOT 0
