ALTER TABLE "replay_camera_sources" ADD COLUMN "installation_id" uuid;--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD COLUMN "reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD COLUMN "report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD COLUMN "last_reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD COLUMN "installation_id" uuid;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD COLUMN "reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD COLUMN "report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD COLUMN "last_reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD COLUMN "installation_id" uuid;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD COLUMN "reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD COLUMN "report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD COLUMN "last_reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD COLUMN "installation_id" uuid;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD COLUMN "reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD COLUMN "report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD COLUMN "last_reported_version" integer;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "venue_edge_config_revisions" ADD COLUMN "commissioning_installation_id" uuid;--> statement-breakpoint
ALTER TABLE "venue_edge_config_revisions" ADD COLUMN "source_report_version" integer;--> statement-breakpoint
ALTER TABLE "venue_edge_config_revisions" ADD COLUMN "source_report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD COLUMN "last_report_version" integer;--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD COLUMN "last_report_checksum_sha256" text;--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD COLUMN "last_reported_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX "venue_edge_installations_tenant_location_id_unique" ON "venue_edge_installations" USING btree ("tenant_id","location_id","id");--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD CONSTRAINT "replay_camera_sources_tenant_location_installation_fk" FOREIGN KEY ("tenant_id","location_id","installation_id") REFERENCES "public"."venue_edge_installations"("tenant_id","location_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD CONSTRAINT "replay_recorders_tenant_location_installation_fk" FOREIGN KEY ("tenant_id","location_id","installation_id") REFERENCES "public"."venue_edge_installations"("tenant_id","location_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD CONSTRAINT "replay_source_policies_tenant_location_installation_fk" FOREIGN KEY ("tenant_id","location_id","installation_id") REFERENCES "public"."venue_edge_installations"("tenant_id","location_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD CONSTRAINT "replay_source_routes_tenant_location_installation_fk" FOREIGN KEY ("tenant_id","location_id","installation_id") REFERENCES "public"."venue_edge_installations"("tenant_id","location_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_edge_config_revisions" ADD CONSTRAINT "venue_edge_config_revisions_commissioning_installation_fk" FOREIGN KEY ("tenant_id","location_id","commissioning_installation_id") REFERENCES "public"."venue_edge_installations"("tenant_id","location_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "replay_camera_sources_installation_active_idx" ON "replay_camera_sources" USING btree ("tenant_id","location_id","installation_id") WHERE "replay_camera_sources"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "replay_recorders_installation_active_idx" ON "replay_recorders" USING btree ("tenant_id","location_id","installation_id") WHERE "replay_recorders"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "replay_source_policies_installation_active_idx" ON "replay_source_policies" USING btree ("tenant_id","location_id","installation_id") WHERE "replay_source_policies"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "replay_source_routes_installation_active_idx" ON "replay_source_routes" USING btree ("tenant_id","location_id","installation_id") WHERE "replay_source_routes"."retired_at" is null;--> statement-breakpoint
CREATE INDEX "venue_edge_config_revisions_commissioning_lineage_idx" ON "venue_edge_config_revisions" USING btree ("tenant_id","location_id","commissioning_installation_id","source_report_version");--> statement-breakpoint
CREATE INDEX "venue_edge_installations_location_active_idx" ON "venue_edge_installations" USING btree ("tenant_id","location_id") WHERE "venue_edge_installations"."retired_at" is null;--> statement-breakpoint
ALTER TABLE "replay_camera_sources" ADD CONSTRAINT "replay_camera_sources_report_lineage_valid" CHECK (("replay_camera_sources"."reported_version" is null or "replay_camera_sources"."reported_version" > 0) and ("replay_camera_sources"."last_reported_version" is null or "replay_camera_sources"."last_reported_version" > 0) and ("replay_camera_sources"."reported_version" is null or "replay_camera_sources"."last_reported_version" is null or "replay_camera_sources"."last_reported_version" >= "replay_camera_sources"."reported_version") and ("replay_camera_sources"."report_checksum_sha256" is null or length("replay_camera_sources"."report_checksum_sha256") > 0));--> statement-breakpoint
ALTER TABLE "replay_recorders" ADD CONSTRAINT "replay_recorders_report_lineage_valid" CHECK (("replay_recorders"."reported_version" is null or "replay_recorders"."reported_version" > 0) and ("replay_recorders"."last_reported_version" is null or "replay_recorders"."last_reported_version" > 0) and ("replay_recorders"."reported_version" is null or "replay_recorders"."last_reported_version" is null or "replay_recorders"."last_reported_version" >= "replay_recorders"."reported_version") and ("replay_recorders"."report_checksum_sha256" is null or length("replay_recorders"."report_checksum_sha256") > 0));--> statement-breakpoint
ALTER TABLE "replay_source_policies" ADD CONSTRAINT "replay_source_policies_report_lineage_valid" CHECK (("replay_source_policies"."reported_version" is null or "replay_source_policies"."reported_version" > 0) and ("replay_source_policies"."last_reported_version" is null or "replay_source_policies"."last_reported_version" > 0) and ("replay_source_policies"."reported_version" is null or "replay_source_policies"."last_reported_version" is null or "replay_source_policies"."last_reported_version" >= "replay_source_policies"."reported_version") and ("replay_source_policies"."report_checksum_sha256" is null or length("replay_source_policies"."report_checksum_sha256") > 0));--> statement-breakpoint
ALTER TABLE "replay_source_routes" ADD CONSTRAINT "replay_source_routes_report_lineage_valid" CHECK (("replay_source_routes"."reported_version" is null or "replay_source_routes"."reported_version" > 0) and ("replay_source_routes"."last_reported_version" is null or "replay_source_routes"."last_reported_version" > 0) and ("replay_source_routes"."reported_version" is null or "replay_source_routes"."last_reported_version" is null or "replay_source_routes"."last_reported_version" >= "replay_source_routes"."reported_version") and ("replay_source_routes"."report_checksum_sha256" is null or length("replay_source_routes"."report_checksum_sha256") > 0));--> statement-breakpoint
ALTER TABLE "venue_edge_config_revisions" ADD CONSTRAINT "venue_edge_config_revisions_report_lineage_consistent" CHECK (("venue_edge_config_revisions"."commissioning_installation_id" is null and "venue_edge_config_revisions"."source_report_version" is null and "venue_edge_config_revisions"."source_report_checksum_sha256" is null) or ("venue_edge_config_revisions"."commissioning_installation_id" is not null and "venue_edge_config_revisions"."source_report_version" > 0 and coalesce(length("venue_edge_config_revisions"."source_report_checksum_sha256"), 0) > 0));--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD CONSTRAINT "venue_edge_installations_report_version_positive" CHECK ("venue_edge_installations"."last_report_version" is null or "venue_edge_installations"."last_report_version" > 0);--> statement-breakpoint
ALTER TABLE "venue_edge_installations" ADD CONSTRAINT "venue_edge_installations_report_lineage_consistent" CHECK (("venue_edge_installations"."last_report_version" is null and "venue_edge_installations"."last_report_checksum_sha256" is null and "venue_edge_installations"."last_reported_at" is null) or ("venue_edge_installations"."last_report_version" is not null and coalesce(length("venue_edge_installations"."last_report_checksum_sha256"), 0) > 0 and "venue_edge_installations"."last_reported_at" is not null));
